runtime: java17 
instance_class: F1

entrypoint: java -jar target/spring-boot-thymeleaf-example-0.0.1-SNAPSHOT.jar

handlers:
  - url: /.*
    script: this field is required, but ignored Limita instâncias para evitar custos